services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: go-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data: