services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: go-backend
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
